# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1207dddbdd67a2389978afe858ffa671fac1a81b5d7985dcb143ab0018ef50357eb1b9ddda7d38fa9786acf2f5c39e23495927d384334c9bbb3d9c4e49aa171

test:
  secret_key_base: 22327e6c7eae6554efdf19bd9fc145d68136f082be01168f9bed30a1612a1ceb9c811cd001a2660877910e16081d9a1880f988f44a1b79598dc91acba049ea40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
